name: Gongmeda Action

on: [pull_request]

jobs:
  Gongmeda-Action:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run Install
        run: npm install
      - name: Run Lint
        run: npm run lint
